# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoProject < Formula
  desc "Go project template"
  homepage "https://github.com/zackijack/go-project"
  version "0.1.5"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zackijack/go-project/releases/download/v0.1.5/go-project_Darwin_x86_64.tar.gz"
      sha256 "2f87df77db1c1f99fdf983cc3b35d7c7c14a1d8ecd1ff93c88a0be27c540b397"
    end
    if Hardware::CPU.arm?
      url "https://github.com/zackijack/go-project/releases/download/v0.1.5/go-project_Darwin_arm64.tar.gz"
      sha256 "b568614c88030d4f2d3ed79006c88635070bc6e45a151542fbaf09aae6a8b2a3"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zackijack/go-project/releases/download/v0.1.5/go-project_Linux_x86_64.tar.gz"
      sha256 "8b822ea17d1d77ff9b098dbdbd98c75e5a51797dc61834bcda983109ce50943f"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/zackijack/go-project/releases/download/v0.1.5/go-project_Linux_arm.tar.gz"
      sha256 "5ed9625297c66ade192d0d3d56047554c6d9d6f730de0127068ec78361b2f6e9"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackijack/go-project/releases/download/v0.1.5/go-project_Linux_arm64.tar.gz"
      sha256 "8665db26893459ba2a653259f32e26a394ad2b7823596429272aeb486b7342c0"
    end
  end

  def install
    bin.install "go-project"

    output = Utils.safe_popen_read({ "SHELL" => "bash" }, bin/"go-project", "completion", "bash")
    (bash_completion/"go-project").write output

    output = Utils.safe_popen_read({ "SHELL" => "zsh" }, bin/"go-project", "completion", "zsh")
    (zsh_completion/"_go-project").write output
  end

  test do
    system "#{bin}/go-project version"
  end
end
