# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoProject < Formula
  desc "Go project template"
  homepage "https://github.com/zackijack"
  version "0.1.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zackijack/go-project/releases/download/v0.1.3/go-project_Darwin_x86_64.tar.gz"
      sha256 "c869235257421c159287322e755f01bf4bb4ebbe96a315f14cf4ece685651b00"
    end
    if Hardware::CPU.arm?
      url "https://github.com/zackijack/go-project/releases/download/v0.1.3/go-project_Darwin_arm64.tar.gz"
      sha256 "eb0360c37b7342b19b78c6ab410e27334608e25ba7095648eca18f779c2e3944"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zackijack/go-project/releases/download/v0.1.3/go-project_Linux_x86_64.tar.gz"
      sha256 "4d742e96ffa5c76f616b04ec10c01f26ba13fe02ed9fedd09d754d9d93622d7a"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/zackijack/go-project/releases/download/v0.1.3/go-project_Linux_arm.tar.gz"
      sha256 "63ca5b954c13108f3fb238fabde530b882b9e5a87d1d0df9130d1c37022b2b52"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackijack/go-project/releases/download/v0.1.3/go-project_Linux_arm64.tar.gz"
      sha256 "4e69c2db76bd4ccb0ce49c498c41a282059a4edb5f687936688a7e02faf8adbe"
    end
  end

  def install
    bin.install "go-project"

    output = Utils.safe_popen_read({ "SHELL" => "bash" }, bin/"go-project", "completion", "bash")
    (bash_completion/"go-project").write output

    output = Utils.safe_popen_read({ "SHELL" => "zsh" }, bin/"go-project", "completion", "zsh")
    (zsh_completion/"_go-project").write output
  end

  test do
    system "#{bin}/go-project version"
  end
end
