# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoProject < Formula
  desc "Go project template"
  homepage "https://github.com/zackijack/go-project"
  version "0.1.4"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zackijack/go-project/releases/download/v0.1.4/go-project_Darwin_x86_64.tar.gz"
      sha256 "c442b9e469821e985366341c10230b914f301186d8fa4ec8cbb82523f33db98e"
    end
    if Hardware::CPU.arm?
      url "https://github.com/zackijack/go-project/releases/download/v0.1.4/go-project_Darwin_arm64.tar.gz"
      sha256 "f74a1751930bf7255c95e0e62491a756be9e47ba1c87b77dd4af4559cdb457f7"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zackijack/go-project/releases/download/v0.1.4/go-project_Linux_x86_64.tar.gz"
      sha256 "19f41e6c3c7b20c985d21c67ffb933af3d7dd5b153ccf60c7e3e1b420fdf8ae0"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/zackijack/go-project/releases/download/v0.1.4/go-project_Linux_arm.tar.gz"
      sha256 "793283a8fd71684cbd922638753cd0d3bf7d97c9102ba72f1f0ca890f6172de2"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackijack/go-project/releases/download/v0.1.4/go-project_Linux_arm64.tar.gz"
      sha256 "d7cb533ae9ab857bc13b787c59a587f96c2f96de39539d775c2ffac4742b4d66"
    end
  end

  def install
    bin.install "go-project"

    output = Utils.safe_popen_read({ "SHELL" => "bash" }, bin/"go-project", "completion", "bash")
    (bash_completion/"go-project").write output

    output = Utils.safe_popen_read({ "SHELL" => "zsh" }, bin/"go-project", "completion", "zsh")
    (zsh_completion/"_go-project").write output
  end

  test do
    system "#{bin}/go-project version"
  end
end
